# Generated by Django 5.0.6 on 2024-06-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='voice_acting_team',
        ),
    ]
