# Generated by Django 5.0.6 on 2024-06-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_episode_voice_acting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='voice_acting_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.voiceactingteam'),
            preserve_default=False,
        ),
    ]
