# Generated by Django 5.0.6 on 2024-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_room_anime_alter_room_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
