# Generated by Django 5.0.6 on 2024-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
